import { TrackerItem } from '../types/item.types';
import { Species } from '../types/animal.types';

export const TRACKED_ITEMS: Record<string, TrackerItem> = {
  apple_slice: {
    id: 'apple_slice',
    name: 'Apple Slice',
    description: 'A fresh, sweet slice of crisp local apple. Wholesome and organic.',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/apple-slice.png',
    cost: 15,
    compatibleSpecies: [Species.SMALL_ANIMAL, Species.BIRD, Species.EXOTIC_SMALL],
    hungerValue: 20,
    xpBonusValue: 5
  },
  bird_seed: {
    id: 'bird_seed',
    name: 'Organic Bird Seed',
    description: 'A rich mixture of sunflower seeds, millet, and oats. Packed with energy.',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/bird-seed.png',
    cost: 10,
    compatibleSpecies: [Species.BIRD],
    hungerValue: 25,
    xpBonusValue: 5
  },
  carrot: {
    id: 'carrot',
    name: 'Crispy Sweet Carrot',
    description: 'Fresh from the garden, crunchy and bright orange. Excellent for gnawing!',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/carrot.png',
    cost: 12,
    compatibleSpecies: [Species.SMALL_ANIMAL, Species.EXOTIC_SMALL],
    hungerValue: 22,
    xpBonusValue: 5
  },
  cat_treat: {
    id: 'cat_treat',
    name: 'Savory Salmon Bites',
    description: 'Delectable, melt-in-the-mouth bites made from sustainably caught salmon.',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/cat-treat.png',
    cost: 18,
    compatibleSpecies: [Species.CAT],
    hungerValue: 30,
    xpBonusValue: 10
  },
  hay_strands: {
    id: 'hay_strands',
    name: 'Fragrant Timothy Hay',
    description: 'Sweet-smelling, fiber-rich hay that promotes healthy digestion.',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/hay-strands.png',
    cost: 8,
    compatibleSpecies: [Species.SMALL_ANIMAL, Species.EXOTIC_SMALL, Species.EXOTIC_LARGE],
    hungerValue: 15,
    xpBonusValue: 3
  },
  lettuce_leaf: {
    id: 'lettuce_leaf',
    name: 'Crisp Lettuce Leaf',
    description: 'Hydrating, crisp green leaf. Refreshing on a warm afternoon.',
    category: 'Treat',
    rarity: 'Common',
    image: './src/assets/images/items/lettuce-leaf.png',
    cost: 6,
    compatibleSpecies: [Species.SMALL_ANIMAL, Species.REPTILE, Species.EXOTIC_SMALL, Species.EXOTIC_LARGE],
    hungerValue: 12,
    xpBonusValue: 2
  },
  cream_food_bowl: {
    id: 'cream_food_bowl',
    name: 'Ceramic Cream Bowl',
    description: 'A beautiful, sturdy ceramic dish finished in a warm pastel cream glaze.',
    category: 'Bowl',
    rarity: 'Common',
    image: './src/assets/images/items/cream-food-bowl.png',
    cost: 25,
    compatibleSpecies: [Species.DOG, Species.CAT, Species.SMALL_ANIMAL],
    isDecoratable: true,
    decorType: 'floor',
    width: 24,
    height: 24
  },
  pet_food_bowl_pink: {
    id: 'pet_food_bowl_pink',
    name: 'Petal Pink Food Bowl',
    description: 'Charming ceramic plate with a glossy pink finish, ideal for dainty eaters.',
    category: 'Bowl',
    rarity: 'Common',
    image: './src/assets/images/items/pet-food-bowl-pink.png',
    cost: 25,
    compatibleSpecies: [Species.DOG, Species.CAT, Species.SMALL_ANIMAL],
    isDecoratable: true,
    decorType: 'floor',
    width: 24,
    height: 24
  },
  metal_pet_bowl: {
    id: 'metal_pet_bowl',
    name: 'Stainless Steel Bowl',
    description: 'Durable, easy-to-clean standard steel dish with a non-slip rubber ring.',
    category: 'Bowl',
    rarity: 'Common',
    image: './src/assets/images/items/metal-pet-bowl.png',
    cost: 20,
    compatibleSpecies: [Species.DOG, Species.CAT],
    isDecoratable: true,
    decorType: 'floor',
    width: 24,
    height: 24
  },
  water_bowl: {
    id: 'water_bowl',
    name: 'Splashy Blue Water Bowl',
    description: 'Filled with crisp morning water, reflecting beautiful, gentle light.',
    category: 'Bowl',
    rarity: 'Common',
    image: './src/assets/images/items/water-bowl.png',
    cost: 20,
    compatibleSpecies: [Species.DOG, Species.CAT, Species.SMALL_ANIMAL, Species.BIRD, Species.REPTILE],
    isDecoratable: true,
    decorType: 'floor',
    width: 24,
    height: 24
  },
  raised_feeder_stand: {
    id: 'raised_feeder_stand',
    name: 'Raised Wooden Feeder',
    description: 'Beautifully carved cedar stand that holds food and water at joint-friendly heights.',
    category: 'Bowl',
    rarity: 'Rare',
    image: './src/assets/images/items/raised-feeder-stand.png',
    cost: 65,
    compatibleSpecies: [Species.DOG, Species.CAT],
    isDecoratable: true,
    decorType: 'floor',
    width: 36,
    height: 24
  },
  catnip_mouse_toy: {
    id: 'catnip_mouse_toy',
    name: 'Catnip Plusha Mouse',
    description: 'Cute fabric mouse stuffed with premium organic catnip for frantic feline fun.',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/catnip-mouse-toy.png',
    cost: 20,
    compatibleSpecies: [Species.CAT],
    happinessValue: 25,
    xpBonusValue: 8
  },
  mylar_ball: {
    id: 'mylar_ball',
    name: 'Sparkly Mylar Ball',
    description: 'Shiny, lightweight ball that crinkles satisfyingly when batted around.',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/mylar-ball.png',
    cost: 15,
    compatibleSpecies: [Species.CAT],
    happinessValue: 18,
    xpBonusValue: 5
  },
  feather_toy: {
    id: 'feather_toy',
    name: 'Chasing Feather Stick',
    description: 'A flexible wand featuring colorful, floaty feathers that dance in the air.',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/feather-toy.png',
    cost: 25,
    compatibleSpecies: [Species.CAT, Species.BIRD],
    happinessValue: 30,
    xpBonusValue: 10
  },
  tennis_ball: {
    id: 'tennis_ball',
    name: 'Sunny Tennis Ball',
    description: 'Bouncy, fuzzy neon-green sphere. Absolutely irresistible to dogs!',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/tennis-ball.png',
    cost: 10,
    compatibleSpecies: [Species.DOG],
    happinessValue: 20,
    xpBonusValue: 6
  },
  rope_dog_toy: {
    id: 'rope_dog_toy',
    name: 'Knotted Cotton Rope',
    description: 'Soft, thick cotton rope with chunky knots, perfect for a cozy game of tug.',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/rope-dog-toy.png',
    cost: 22,
    compatibleSpecies: [Species.DOG],
    happinessValue: 24,
    xpBonusValue: 8
  },
  heavy_tug_rope: {
    id: 'heavy_tug_rope',
    name: 'Heavy Duty Tug Rope',
    description: 'Sturdy braided rope crafted for highly enthusiastic pullers and active dogs.',
    category: 'Toy',
    rarity: 'Rare',
    image: './src/assets/images/items/heavy-tug-rope.png',
    cost: 45,
    compatibleSpecies: [Species.DOG],
    happinessValue: 35,
    xpBonusValue: 15
  },
  kong_toy: {
    id: 'kong_toy',
    name: 'Cozy Stuffable Cone',
    description: 'Durable rubber cone you can stuff with tasty peanut butter to keep them happy for hours.',
    category: 'Toy',
    rarity: 'Rare',
    image: './src/assets/images/items/kong-toy.png',
    cost: 40,
    compatibleSpecies: [Species.DOG],
    happinessValue: 32,
    xpBonusValue: 12
  },
  treat_ball: {
    id: 'treat_ball',
    name: 'Roll-and-Seek Treat Ball',
    description: 'A hollow sphere that slowly dispenses kibble when rolled back and forth.',
    category: 'Toy',
    rarity: 'Rare',
    image: './src/assets/images/items/treat-ball.png',
    cost: 50,
    compatibleSpecies: [Species.DOG, Species.CAT, Species.SMALL_ANIMAL],
    happinessValue: 30,
    xpBonusValue: 12
  },
  rubber_duck: {
    id: 'rubber_duck',
    name: 'Squeaky Rubber Duck',
    description: 'An adorable classic yellow buddy that lets out a delightful, cheerful squeak.',
    category: 'Toy',
    rarity: 'Common',
    image: './src/assets/images/items/rubber-duck.png',
    cost: 18,
    compatibleSpecies: [Species.DOG, Species.CAT],
    happinessValue: 22,
    xpBonusValue: 7
  },
  laser_pointer: {
    id: 'laser_pointer',
    name: 'Twinkling Laser Pointer',
    description: 'Projects a bright, evasive red dot. The ultimate target of wild chases!',
    category: 'Toy',
    rarity: 'Rare',
    image: './src/assets/images/items/laser-pointer.png',
    cost: 55,
    compatibleSpecies: [Species.CAT, Species.DOG],
    happinessValue: 40,
    xpBonusValue: 15
  }
};
